### ISSUE TITLE
Sorry was looking around and saw you had a wizard

### ISSUE THREAD

**Issue by SerpentDrago** [turtlestv/misc#1]
https://github.com/drinfernoo/plugin.program.aftermath

Thats a Updated version of the AftermathWizard . thats being actively worked on . if you know how to setup aftermath you pritty much know how to setup that . few tweaks to the builds.txt file , 

We just need to add exodus redux to the saveing . and its pretty much updtodate . Its all the features of aftermath with a few tweaks and updates . 

If you have any questions We have a telegram channel for Aftermath and its forks send me your telegram user and i'll invite you

**Comment by turtlestv** [comment]
@turtletv

Thanks.
